### ISSUE TITLE
looking for version information.

### ISSUE THREAD

**Issue by chuchienshu** [Johswald/Bayesian-FlowNet#2]
Hi, @Johswald looks like you didn't open your version information, including the os' version and tensorflow's version. would you mind tell me about that? Thanks!

**Comment by Johswald** [comment]
Hi! Working on a server from my uni:
- Ubuntu 16.04.3
- Tensorflow version 1.3.0
Is something not working for you?
Sorry my late reply

**Comment by chuchienshu** [comment]
Hi, @Johswald  it's fine. Thanks for your reply. And I have to say, your function  warp(imgs_0, imgs_1, flows, name) defined at flownet.py looks not right.
would you mind take your time to look up the relevant code at [https://github.com/liruoteng/OpticalFlowToolkit/blob/master/lib/flowlib.py](https://github.com/liruoteng/OpticalFlowToolkit/blob/master/lib/flowlib.py) (line 364)?
BTW, I wanna you know , that code  present worse performence. please @chuchienshu, if you want me get your response at the first time. Thanks, again.

**Comment by Johswald** [comment]
Hi @chuchienshu,
thanks for your suggestions. Yes, my warp was very simple and just for testing. thank you for the link.
What do you mean by "that code present worse performence"?
